cc_library(
    name = 'protobuf',
    deps = [
        '//thirdparty/protobuf-3.6.1:protobuf',
    ]
)
cc_library(
    name = 'protoc',
    deps = [
        '//thirdparty/protobuf-3.6.1:protoc',
    ]
)